// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: proto/loader.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerStatusCommand int32

const (
	PowerStatusCommand_Shutdown PowerStatusCommand = 0
	PowerStatusCommand_Restart  PowerStatusCommand = 1
	PowerStatusCommand_Logoff   PowerStatusCommand = 2
)

// Enum value maps for PowerStatusCommand.
var (
	PowerStatusCommand_name = map[int32]string{
		0: "Shutdown",
		1: "Restart",
		2: "Logoff",
	}
	PowerStatusCommand_value = map[string]int32{
		"Shutdown": 0,
		"Restart":  1,
		"Logoff":   2,
	}
)

func (x PowerStatusCommand) Enum() *PowerStatusCommand {
	p := new(PowerStatusCommand)
	*p = x
	return p
}

func (x PowerStatusCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerStatusCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_loader_proto_enumTypes[0].Descriptor()
}

func (PowerStatusCommand) Type() protoreflect.EnumType {
	return &file_proto_loader_proto_enumTypes[0]
}

func (x PowerStatusCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerStatusCommand.Descriptor instead.
func (PowerStatusCommand) EnumDescriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  int32  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_loader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PowerCtlOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order PowerStatusCommand `protobuf:"varint,1,opt,name=order,proto3,enum=PowerStatusCommand" json:"order,omitempty"`
}

func (x *PowerCtlOrder) Reset() {
	*x = PowerCtlOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_loader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerCtlOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerCtlOrder) ProtoMessage() {}

func (x *PowerCtlOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerCtlOrder.ProtoReflect.Descriptor instead.
func (*PowerCtlOrder) Descriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{1}
}

func (x *PowerCtlOrder) GetOrder() PowerStatusCommand {
	if x != nil {
		return x.Order
	}
	return PowerStatusCommand_Shutdown
}

var File_proto_loader_proto protoreflect.FileDescriptor

var file_proto_loader_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x3a, 0x0a, 0x0d, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x74, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x29, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2a, 0x3b, 0x0a, 0x12,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x66, 0x66, 0x10, 0x02, 0x32, 0x2f, 0x0a, 0x06, 0x4c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x08, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x74, 0x6c, 0x12,
	0x0e, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x74, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a,
	0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_loader_proto_rawDescOnce sync.Once
	file_proto_loader_proto_rawDescData = file_proto_loader_proto_rawDesc
)

func file_proto_loader_proto_rawDescGZIP() []byte {
	file_proto_loader_proto_rawDescOnce.Do(func() {
		file_proto_loader_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_loader_proto_rawDescData)
	})
	return file_proto_loader_proto_rawDescData
}

var file_proto_loader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_loader_proto_goTypes = []interface{}{
	(PowerStatusCommand)(0), // 0: PowerStatusCommand
	(*Result)(nil),          // 1: Result
	(*PowerCtlOrder)(nil),   // 2: PowerCtlOrder
}
var file_proto_loader_proto_depIdxs = []int32{
	0, // 0: PowerCtlOrder.order:type_name -> PowerStatusCommand
	2, // 1: Loader.PowerCtl:input_type -> PowerCtlOrder
	1, // 2: Loader.PowerCtl:output_type -> Result
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_loader_proto_init() }
func file_proto_loader_proto_init() {
	if File_proto_loader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_loader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_loader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerCtlOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_loader_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loader_proto_goTypes,
		DependencyIndexes: file_proto_loader_proto_depIdxs,
		EnumInfos:         file_proto_loader_proto_enumTypes,
		MessageInfos:      file_proto_loader_proto_msgTypes,
	}.Build()
	File_proto_loader_proto = out.File
	file_proto_loader_proto_rawDesc = nil
	file_proto_loader_proto_goTypes = nil
	file_proto_loader_proto_depIdxs = nil
}
